micronaut:
  application:
    name: paromuz-demo
  server:
    port: 8080

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'postgres'
    schema-generate: none # because of flyway !!
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true